GET https://{{BASE_URI}}/
Authorization: Bearer {{TOKEN}}

GET https://{{BASE_URI}}/feedback
Authorization: Bearer {{TOKEN}}

GET https://{{BASE_URI}}/status Authorization: Bearer {{TOKEN}}

POST https://{{BASE_URI}}/hook
Content-Type: application/json

{
    "messrge": "nada"
}

PUT https://{{BASE_URI}}/feedback/2
Content-Type: application/json

{
    "category": "categoría",
    "content": "vacio"
}

POST https://{{BASE_URI}}/feedback
Content-Type: application/json

{
    "category": "nada",
    "content": "vacio"
}

POST http://{{BASE_URI}}/feedback
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "category": "nada1",
    "content": "este"
}

GET http://{{BASE_URI}}/feedback/3
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

PUT http://{{BASE_URI}}/feedback/3
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "category": "nada1",
    "content": "o este"
}

GET http://{{BASE_URI}}/feedback
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

GET http://{{BASE_URI}}/feedback/8
Content-Type: application/json

GET https://{{BASE_URI}}/feedback
Authorization: Bearer {{TOKEN}}

GET https://{{BASE_URI}}/
Authorization: Bearer {{TOKEN}}
Content-Type: application/json
