GET https://attgsup.territoriolinux.es/

GET https://attgsup.territoriolinux.es/feedback

GET https://attgsup.territoriolinux.es/status

POST https://attgsup.territoriolinux.es/hook
Content-Type: application/json

{
    "messrge": "nada"
}

PUT https://attgsup.territoriolinux.es/feedback/2
Content-Type: application/json

{
    "category": "categoría",
    "content": "vacio"
}

POST https://attgsup.territoriolinux.es/feedback
Content-Type: application/json

{
    "category": "nada",
    "content": "vacio"
}

POST http://localhost:8080/feedback
Authorization: Bearer XXXXX
Content-Type: application/json

{
    "category": "nada1",
    "content": "este"
}

GET http://localhost:8080/feedback/3
Authorization: Bearer XXXXX
Content-Type: application/json

PUT http://localhost:8080/feedback/3
Authorization: Bearer XXXXX
Content-Type: application/json

{
    "category": "nada1",
    "content": "o este"
}

GET http://localhost:8080/feedback
Authorization: Bearer XXXXX
Content-Type: application/json

GET http://localhost:8080/feedback/8
Content-Type: application/json

GET http://localhost:8080/feedback
Authorization: Bearer XXXXX
